Repository mesonbuild/meson, pull requests merged in 2018-07, with the labels that each got.

#3816 Don't let build_always take precedence over build_by_default
  mesonbuild/build.py
  run_unittests.py
  test cases/common/137 build by default/checkexists.py
  test cases/common/137 build by default/meson.build
Labels: regression

#3833 find_library: Only run link test on system dirs
  mesonbuild/compilers/c.py
  test cases/common/146 C and CPP link/foo.cpp
  test cases/common/146 C and CPP link/foobar.c
Labels: regression

#3838 gnome.gtkdoc: Don't treat install_dir as a file option
  mesonbuild/modules/gnome.py
  test cases/frameworks/10 gtk-doc/doc/meson.build
  test cases/frameworks/10 gtk-doc/installed_files.txt
Labels: regression

#3845 Add missing method on external library object: type_name()
  docs/markdown/Reference-manual.md
  mesonbuild/dependencies/base.py
  mesonbuild/interpreter.py
  test cases/common/146 C and CPP link/meson.build
Labels: dependencies

#3851 Fix searching of shared libraries on OpenBSD
  mesonbuild/backend/ninjabackend.py
  mesonbuild/compilers/c.py
  mesonbuild/compilers/fortran.py
  mesonbuild/mesonlib.py
  run_unittests.py
Labels: *BSD, regression

#3955 gnome: Fix building gir with asan again
  mesonbuild/modules/gnome.py
Labels: gnome, regression
