Repository mesonbuild/meson, pull requests merged in 2018-04, with the labels that each got.

#3363 Remove commit_zero recommendation from wrap documentation, use action commit [skip ci]
  docs/markdown/Adding-new-projects-to-wrapdb.md
Labels: documentation, subprojects/wraps

#3326 [Qt module] Add File object support for generated or not qrc files
  mesonbuild/modules/qt.py
  test cases/frameworks/4 qt/meson.build
  test cases/frameworks/4 qt/subfolder/generator.py
  test cases/frameworks/4 qt/subfolder/main.cpp
  test cases/frameworks/4 qt/subfolder/meson.build
  test cases/frameworks/4 qt/subfolder/resources/stuff4.qrc.in
Labels: qt

#3093 Improve generation of pkg-config files for static only libraries. (closes #3074)
  docs/markdown/snippets/pkg-config-fix-static-only.md
  mesonbuild/modules/pkgconfig.py
  run_unittests.py
  test cases/common/51 pkgconfig-gen/dependencies/meson.build
  test cases/unit/28 pkgconfig use libraries/app/app.c
  test cases/unit/28 pkgconfig use libraries/app/meson.build
  test cases/unit/28 pkgconfig use libraries/lib/liba.c
  test cases/unit/28 pkgconfig use libraries/lib/libb.c
  test cases/unit/28 pkgconfig use libraries/lib/meson.build
Labels: WIP

#3421 fix fallback variable name
  manual tests/2 multiwrap/meson.build
Labels: bug

#2936 Partial dependencies
  docs/markdown/Reference-manual.md
  docs/markdown/snippets/partial-dependencies.md
  mesonbuild/dependencies/base.py
  mesonbuild/interpreter.py
  test cases/common/191 partial dependency/declare_dependency/headers/foo.c
  test cases/common/191 partial dependency/declare_dependency/headers/foo.h
  test cases/common/191 partial dependency/declare_dependency/main.c
  test cases/common/191 partial dependency/declare_dependency/meson.build
  test cases/common/191 partial dependency/declare_dependency/other.c
  test cases/common/191 partial dependency/meson.build
  test cases/frameworks/1 boost/meson.build
  test cases/frameworks/1 boost/partial_dep/foo.cpp
  test cases/frameworks/1 boost/partial_dep/foo.hpp
  test cases/frameworks/1 boost/partial_dep/main.cpp
  test cases/frameworks/1 boost/partial_dep/meson.build
Labels: dependencies

#3314 Add test(depends) keyword parameter
  docs/markdown/Reference-manual.md
  docs/markdown/snippets/test-depends.md
  mesonbuild/backend/backends.py
  mesonbuild/interpreter.py
  test cases/common/188 test depends/gen.py
  test cases/common/188 test depends/main.c
  test cases/common/188 test depends/meson.build
  test cases/common/188 test depends/test.py
Labels: dependencies, enhancement, test targets

#3427 Update 'manual tests/2 multiwrap' libpng dependency to 1.6.34
  manual tests/2 multiwrap/subprojects/libpng.wrap
Labels: bug, meson tests

#3425 Rename common tests to remove numeric duplicates
  test cases/common/196 same target name/file.c
  test cases/common/196 same target name/meson.build
  test cases/common/196 same target name/sub/file2.c
  test cases/common/196 same target name/sub/meson.build
  test cases/common/197 test depends/gen.py
  test cases/common/197 test depends/main.c
  test cases/common/197 test depends/meson.build
  test cases/common/197 test depends/test.py
Labels: refactoring

#3391 Don't fail on not-required not-found deps in forcefallback mode
  mesonbuild/dependencies/__init__.py
  mesonbuild/dependencies/base.py
  mesonbuild/interpreter.py
  test cases/unit/27 forcefallback/meson.build
Labels: bug

#3444 ninja backend: Fix shared library symbols path
  mesonbuild/backend/ninjabackend.py
Labels: gstreamer, regression
