Repository mesonbuild/meson, pull requests merged in 2018-03, with the labels that each got.

#3154 Add reference to implicit_include_directories from include_directories()
  docs/markdown/Reference-manual.md
Labels: documentation

#3172 Document wxwidgets dependency, closes #3159 [skip ci]
  docs/markdown/Dependencies.md
Labels: documentation

#3180 Fix a syntax error in an example in 'Generating sources'.
  docs/markdown/Generating-sources.md
Labels: documentation

#3193 Add indentation to 'common/64 custom header generator' test case
  test cases/common/64 custom header generator/meson.build
Labels: refactoring

#3195 Get generated headers from link_whole_targets as meson does for link_targets
  mesonbuild/backend/ninjabackend.py
  test cases/common/180 generator link whole/export.h
  test cases/common/180 generator link whole/generator.py
  test cases/common/180 generator link whole/main.c
  test cases/common/180 generator link whole/meson.build
  test cases/common/180 generator link whole/meson_test_function.tmpl
  test cases/common/180 generator link whole/pull_meson_test_function.c
Labels: bug, dependencies, generators

#3228 Use os.path.dirname() instead of os.path.split(...)[0] in ghwt.py
  ghwt.py
Labels: refactoring

#3205 Use itertools instead of list concatenation, do not use bare except
  mesonbuild/backend/ninjabackend.py
  mesonbuild/build.py
  mesonbuild/compilers/c.py
  mesonbuild/coredata.py
  mesonbuild/scripts/meson_install.py
  test cases/common/72 build always/version_gen.py
Labels: refactoring

#3232 Fix failing tests introduced by #3131
  mesonbuild/modules/pkgconfig.py
Labels: bug

#3241 Use target.get_id() instead of concatenating basename and type_suffix at call site
  mesonbuild/backend/backends.py
  mesonbuild/backend/ninjabackend.py
  mesonbuild/backend/vs2010backend.py
  run_unittests.py
  test cases/common/182 identical target name in subproject flat layout/foo.c
  test cases/common/182 identical target name in subproject flat layout/main.c
  test cases/common/182 identical target name in subproject flat layout/meson.build
  test cases/common/182 identical target name in subproject flat layout/subprojects/subproj/foo.c
  test cases/common/182 identical target name in subproject flat layout/subprojects/subproj/meson.build
Labels: bug

#3253 Fix appveyor failures: do not use PowerShell since it triggers NativeCommandError if pacman prints to stderr
  .appveyor.yml
Labels: CI

#3235 Create a helper for checking if a string has a path component
  mesonbuild/backend/ninjabackend.py
  mesonbuild/build.py
  mesonbuild/interpreter.py
  mesonbuild/mesonlib.py
  mesonbuild/scripts/yelphelper.py
Labels: refactoring

#3223 Add install_data() rename parameter
  docs/markdown/Installing.md
  docs/markdown/Reference-manual.md
  docs/markdown/snippets/install_data-rename.md
  mesonbuild/backend/ninjabackend.py
  mesonbuild/build.py
  mesonbuild/interpreter.py
  test cases/common/12 data/installed_files.txt
  test cases/common/12 data/meson.build
  test cases/common/12 data/to_be_renamed_1.txt
  test cases/common/12 data/to_be_renamed_3.txt
  test cases/common/12 data/to_be_renamed_4.txt
  test cases/common/12 data/vanishing/to_be_renamed_2.txt
  test cases/failing/70 install_data rename bad size/file1.txt
  test cases/failing/70 install_data rename bad size/file2.txt
  test cases/failing/70 install_data rename bad size/meson.build
Labels: enhancement, install targets

#3274 Fix b_ndebug=if-release silently not working
  mesonbuild/backend/backends.py
  mesonbuild/backend/ninjabackend.py
  mesonbuild/compilers/compilers.py
  run_unittests.py
  test cases/common/185 ndebug if-release enabled/main.c
  test cases/common/185 ndebug if-release enabled/meson.build
  test cases/common/186 ndebug if-release disabled/main.c
  test cases/common/186 ndebug if-release disabled/meson.build
  test cases/unit/25 ndebug if-release/main.c
  test cases/unit/25 ndebug if-release/meson.build
Labels: bug

#3273 Rename '183 as-needed' common test into '184 as-needed'
  test cases/common/183 as-needed/main.cpp
  test cases/common/184 as-needed/config.h
  test cases/common/184 as-needed/libA.cpp
  test cases/common/184 as-needed/libA.h
  test cases/common/184 as-needed/libB.cpp
  test cases/common/184 as-needed/main.cpp
  test cases/common/184 as-needed/meson.build
Labels: refactoring

#3281 docs: fix one 'target' that should be 'host'
  docs/markdown/Cross-compilation.md
Labels: documentation

#3297 Few Intel compiler fixes
  mesonbuild/compilers/compilers.py
Labels: WIP

#3293 Update test() in Reference Manual
  docs/markdown/Reference-manual.md
Labels: documentation

#3288 Enable b_ndebug on VisualStudioCCompiler
  mesonbuild/backend/vs2010backend.py
  mesonbuild/compilers/c.py
  test cases/common/185 ndebug if-release enabled/meson.build
  test cases/common/186 ndebug if-release disabled/meson.build
  test cases/unit/25 ndebug if-release/meson.build
Labels: windows

#3298 Skip CI for documentation-only pull requests
  .appveyor.yml
  .travis.yml
  skip_ci.py
Labels: CI

#3285 Retry downloads in Appveyor
  .appveyor.yml
Labels: CI

#3319 Do not leave open file handlers, use context manager to clean them up
  run_unittests.py
Labels: meson tests, refactoring

#3308 docs: Expand on compiler vs compilee build host and target
  docs/markdown/Cross-compilation.md
Labels: cross, documentation

#3346 Added link to documentation and examples for find_library replacement
  mesonbuild/interpreter.py
Labels: documentation

#3347 Update Pkg-config-files.md [skip ci]
  docs/markdown/Pkg-config-files.md
Labels: documentation
