Repository mesonbuild/meson, pull requests merged in 2018-05, with the labels that each got.

#3507 Fix setting c_args and friends from command line
  mesonbuild/interpreter.py
  mesonbuild/mconf.py
  test cases/common/181 initial c_args/meson.build
Labels: regression

#3530 add linker flag to handle $ORIGIN on OpenBSD
  mesonbuild/compilers/compilers.py
  mesonbuild/mesonlib.py
Labels: *BSD

#3533 gnome: Use the header basename for #include in mkenums_simple
  mesonbuild/modules/gnome.py
  test cases/frameworks/7 gnome/mkenums/meson.build
Labels: bug, gnome, gstreamer

#3491 Qt private headers
  docs/markdown/Qt5-module.md
  docs/markdown/Reference-manual.md
  mesonbuild/dependencies/ui.py
  mesonbuild/interpreter.py
  test cases/frameworks/4 qt/main.cpp
  test cases/frameworks/4 qt/meson.build
Labels: qt
