Repository mesonbuild/meson, pull requests merged in 2019-03, with the labels that each got.

#2601 Add completion scripts for Bash and Zsh
  data/shell-completions/bash/meson
  data/shell-completions/zsh/_meson
  mesonbuild/mesonmain.py
  mesonbuild/mtest.py
Labels: shell completions

#5023 hotdoc: Set gi-c-source-root
  mesonbuild/modules/hotdoc.py
Labels: gstreamer

#5112 replace library type strings with an enum
  mesonbuild/backend/ninjabackend.py
  mesonbuild/compilers/c.py
  mesonbuild/compilers/fortran.py
  mesonbuild/dependencies/base.py
  mesonbuild/interpreter.py
  mesonbuild/mesonlib.py
  run_unittests.py
Labels: refactoring
