Repository mesonbuild/meson, pull requests merged in 2019-11, with the labels that each got.

#6121 Minit templates modularization
  docs/markdown/snippets/new_meson_project_templates.md
  mesonbuild/minit.py
  mesonbuild/templates/__init__.py
  mesonbuild/templates/cpptemplates.py
  mesonbuild/templates/ctemplates.py
  mesonbuild/templates/dlangtemplates.py
  mesonbuild/templates/fortrantemplates.py
  mesonbuild/templates/objctemplates.py
  mesonbuild/templates/rusttemplates.py
  run_unittests.py
  setup.py
Labels: enhancement

#6123 bugfix: fortran compiler assertionerror from 0c22798
  mesonbuild/compilers/fortran.py
  mesonbuild/environment.py
Labels: fortran, regression

#6126 Fix split of CMAKE_PREFIX_PATH under Windows
  mesonbuild/dependencies/base.py
Labels: cmake

#6140 Fix typos found by codespell
  docs/markdown/Build-options.md
  docs/markdown/Builtin-options.md
  docs/markdown/CMake-module.md
  docs/markdown/Continuous-Integration.md
  docs/markdown/Contributing.md
  docs/markdown/Dependencies.md
  docs/markdown/Design-rationale.md
  docs/markdown/FAQ.md
  docs/markdown/Kconfig-module.md
  docs/markdown/Localisation.md
  docs/markdown/Pkg-config-files.md
  docs/markdown/Reference-manual.md
  docs/markdown/Rewriter.md
  docs/markdown/Unit-tests.md
  docs/markdown/Vala.md
  mesonbuild/ast/interpreter.py
  mesonbuild/ast/introspection.py
  mesonbuild/backend/ninjabackend.py
  mesonbuild/cmake/data/run_ctgt.py
  mesonbuild/cmake/fileapi.py
  mesonbuild/cmake/interpreter.py
  mesonbuild/cmake/traceparser.py
  mesonbuild/compilers/compilers.py
  mesonbuild/compilers/cpp.py
  mesonbuild/compilers/cuda.py
  mesonbuild/compilers/mixins/emscripten.py
  mesonbuild/compilers/mixins/visualstudio.py
  mesonbuild/coredata.py
  mesonbuild/dependencies/base.py
  mesonbuild/dependencies/dev.py
  mesonbuild/envconfig.py
  mesonbuild/environment.py
  mesonbuild/interpreter.py
  mesonbuild/interpreterbase.py
  mesonbuild/linkers.py
  mesonbuild/mconf.py
  mesonbuild/mesonlib.py
  mesonbuild/mesonmain.py
  mesonbuild/mintro.py
  mesonbuild/mlog.py
  mesonbuild/modules/cmake.py
  mesonbuild/modules/gnome.py
  mesonbuild/modules/unstable_simd.py
  mesonbuild/mtest.py
  mesonbuild/munstable_coredata.py
  mesonbuild/rewriter.py
  run_unittests.py
  test cases/common/187 find override/otherdir/meson.build
  test cases/common/194 check header/meson.build
  test cases/common/203 function attributes/meson.build
  test cases/common/218 dependency get_variable method/meson.build
  test cases/common/34 has header/meson.build
  test cases/common/62 install subdir/installed_files.txt
  test cases/common/62 install subdir/nested_elided/sub/dircheck/ninth.dat
  test cases/unit/65 cmake parser/meson.build
Labels: documentation, refactoring

#6138 docs: Add backend vs2019 to table in Builtin-options.md [skip ci]
  docs/markdown/Builtin-options.md
Labels: documentation

#6142 mesonbuild/mtest: plumb and report a test's start time
  mesonbuild/mtest.py
Labels: enhancement, meson tests

#6135 Created the filesystem module.
  docs/markdown/Fs-module.md
  docs/markdown/snippets/fsmodule.md
  docs/sitemap.txt
  mesonbuild/interpreter.py
  mesonbuild/modules/__init__.py
  mesonbuild/modules/fs.py
  test cases/common/227 fs module/a_symlink
  test cases/common/227 fs module/meson.build
  test cases/common/227 fs module/subdir/meson.build
  test cases/common/227 fs module/subdir/subdirfile.txt
  test cases/common/227 fs module/subprojects/subbie/meson.build
  test cases/common/227 fs module/subprojects/subbie/subprojectfile.txt
  test cases/common/227 fs module/subprojects/subbie/subsub/meson.build
  test cases/common/227 fs module/subprojects/subbie/subsub/subsubfile.txt
Labels: enhancement

#6171 cmake: Log warnings in CMakeLists.txt
  mesonbuild/cmake/interpreter.py
Labels: cmake

#6173 doc: readme note that can get ninja via pip install ninja [skip ci]
  README.md
Labels: documentation

#6189 docs: fix non-existent "meson rewriter" command in examples [skip ci]
  docs/markdown/Rewriter.md
Labels: documentation

#6177 add bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#6150 fs module; make more robust, dedupe code, add method, add type anno & check
  azure-pipelines.yml
  docs/markdown/Fs-module.md
  mesonbuild/modules/fs.py
  test cases/common/227 fs module/meson.build
Labels: enhancement

#6193 lint+mypy: move to github actions
  .github/workflows/lint_mypy.yml
  .github/workflows/unusedargs_missingreturn.yml
  azure-pipelines.yml
Labels: CI, refactoring

#6200 fortran: note there is no has_function for Fortran
  mesonbuild/compilers/fortran.py
Labels: fortran, parser/interpreter

#6194 dep: Fortran Coarrays-enhance finding by use Pkg-config & CMake
  mesonbuild/dependencies/__init__.py
  mesonbuild/dependencies/coarrays.py
  mesonbuild/dependencies/misc.py
  test cases/fortran/13 coarray/meson.build
Labels: dependencies

#6201 fortran: sync implicit-none args for intel,pgi,gfortran
  mesonbuild/compilers/fortran.py
Labels: fortran

#6199 cmake: Handle CMake system include dirs (closes #6079)
  mesonbuild/backend/ninjabackend.py
  mesonbuild/cmake/common.py
  mesonbuild/cmake/fileapi.py
  mesonbuild/cmake/interpreter.py
  mesonbuild/interpreter.py
  mesonbuild/mlog.py
  run_project_tests.py
  test cases/cmake/13 system includes/meson.build
Labels: cmake

#6226 openbsd: execinfo is not a compiler lib
  mesonbuild/compilers/compilers.py
Labels: *BSD

#6215 dep: MPI make work for intel-cl and improve robustness
  .github/workflows/lint_mypy.yml
  mesonbuild/dependencies/__init__.py
  mesonbuild/dependencies/misc.py
  mesonbuild/dependencies/mpi.py
  mesonbuild/linkers.py
  mesonbuild/mesonlib.py
Labels: dependencies

#6219 Add `fortran_std` project option
  docs/markdown/Builtin-options.md
  docs/markdown/Configuring-a-build-directory.md
  docs/markdown/snippets/fortran_std.md
  mesonbuild/compilers/fortran.py
  test cases/fortran/19 fortran_std/legacy.f
  test cases/fortran/19 fortran_std/meson.build
  test cases/fortran/19 fortran_std/std2003.f90
  test cases/fortran/19 fortran_std/std2008.f90
  test cases/fortran/19 fortran_std/std2018.f90
  test cases/fortran/19 fortran_std/std95.f90
Labels: fortran

#6213 cmake: Uniform target name handling and custom target fixes
  mesonbuild/cmake/data/run_ctgt.py
  mesonbuild/cmake/interpreter.py
  test cases/cmake/2 advanced/installed_files.txt
  test cases/cmake/3 advanced no dep/installed_files.txt
  test cases/cmake/5 object library/subprojects/cmObjLib/CMakeLists.txt
  test cases/cmake/6 object library no dep/subprojects/cmObjLib/CMakeLists.txt
Labels: cmake

#6239 ci: lgtm: configure for Python 3
  lgtm.yml
Labels: CI

#6248 wrap: Resolver.get_git: Factor out --depth argument generation and make sure not to pass None as parameter
  mesonbuild/wrap/wrap.py
Labels: regression, subprojects/wraps

#5989 cmake: Add support for add_custom_target() and add_dependencies()
  mesonbuild/cmake/data/run_ctgt.py
  mesonbuild/cmake/interpreter.py
  mesonbuild/cmake/traceparser.py
  test cases/cmake/8 custom command/subprojects/cmMod/CMakeLists.txt
  test cases/cmake/8 custom command/subprojects/cmMod/args_test.cpp
  test cases/cmake/8 custom command/subprojects/cmMod/cmMod.cpp
  test cases/cmake/8 custom command/subprojects/cmMod/macro_name.cpp
Labels: cmake

#6255 wrap: Redirect stdin to DEVNULL (again)
  mesonbuild/msubprojects.py
Labels: regression, windows

#6265 Fix regular expression for MSVC target arch detection
  mesonbuild/environment.py
Labels: regression, windows

#6261 cmake: Make output_target_map more robust (fixes #6208)
  mesonbuild/cmake/data/run_ctgt.py
  mesonbuild/cmake/interpreter.py
  test cases/cmake/8 custom command/subprojects/cmMod/CMakeLists.txt
  test cases/cmake/8 custom command/subprojects/cmMod/cmMod.cpp
  test cases/cmake/8 custom command/subprojects/cmMod/cp.cpp
  test cases/cmake/8 custom command/subprojects/cmMod/cpyNext.cpp.am
  test cases/cmake/8 custom command/subprojects/cmMod/cpyNext.hpp.am
Labels: cmake

#6250 Update CI Continuous Integration page and add CircleCi example [skip ci]
  docs/markdown/Continuous-Integration.md
Labels: documentation
