Repository mesonbuild/meson, pull requests merged in 2019-06, with the labels that each got.

#5449 compilers/c: Fix removal of name from Combo options for ICL
  mesonbuild/compilers/c.py
Labels: bug

#5459 docs: Add bzip2 to the Users page [skip ci]
  docs/markdown/Users.md
Labels: documentation

#5517 compilers: Fix bitcode and other options for objc code
  mesonbuild/compilers/objc.py
  mesonbuild/compilers/objcpp.py
  run_unittests.py
  test cases/osx/7 bitcode/libbar.mm
  test cases/osx/7 bitcode/libfile.c
  test cases/osx/7 bitcode/libfoo.m
  test cases/osx/7 bitcode/meson.build
  test cases/osx/7 bitcode/vis.h
Labels: macos

#5524 Add ifort on Windows
  mesonbuild/backend/ninjabackend.py
  mesonbuild/compilers/fortran.py
  mesonbuild/dependencies/misc.py
  mesonbuild/environment.py
  mesonbuild/interpreter.py
  run_project_tests.py
  test cases/fortran/10 find library/meson.build
  test cases/fortran/13 coarray/meson.build
  test cases/fortran/6 dynamic/meson.build
Labels: enhancement, windows

#5555 CI: Fortran-specific OpenMP tests
  test cases/fortran/16 openmp/main.f90
  test cases/fortran/16 openmp/meson.build
Labels: CI
