Repository mesonbuild/meson, pull requests merged in 2019-08, with the labels that each got.

#5768 expand tilde ~ in '-Dfoo=~/mylib'
  mesonbuild/interpreter.py
Labels: parser/interpreter, pathlib

#5834 cmake:correct logic for too old cmake
  mesonbuild/cmake/executor.py
Labels: bug, cmake

#5448 Vs backend compiler selection
  docs/markdown/Using-with-Visual-Studio.md
  mesonbuild/backend/backends.py
  mesonbuild/backend/vs2015backend.py
  mesonbuild/backend/vs2017backend.py
  mesonbuild/backend/vs2019backend.py
  mesonbuild/interpreter.py
Labels: windows

#5683 Add test priorities to force test start order
  docs/markdown/Reference-manual.md
  docs/markdown/Unit-tests.md
  mesonbuild/backend/backends.py
  mesonbuild/interpreter.py
  mesonbuild/mintro.py
  test cases/common/224 test priorities/meson.build
  test cases/common/224 test priorities/test.sh
Labels: enhancement

#5852 environment: Fix detection of MSVC arch on arm64
  mesonbuild/environment.py
Labels: cross, windows
