Repository mesonbuild/meson, pull requests merged in 2020-04, with the labels that each got.

#6843 CI: Maintain docker images with GitHub Actions
  .github/workflows/images.yml
  .github/workflows/os_comp.yml
  ci/ciimage/.gitignore
  ci/ciimage/arch/Dockerfile
  ci/ciimage/arch/image.json
  ci/ciimage/arch/install.sh
  ci/ciimage/build.py
  ci/ciimage/common.sh
  ci/ciimage/eoan/Dockerfile
  ci/ciimage/eoan/image.json
  ci/ciimage/eoan/install.sh
  ci/ciimage/eoan/test.sh
  ci/ciimage/fedora/Dockerfile
  ci/ciimage/fedora/image.json
  ci/ciimage/fedora/install.sh
  ci/ciimage/opensuse/Dockerfile
  ci/ciimage/opensuse/image.json
  ci/ciimage/opensuse/install.sh
  mesonbuild/interpreter.py
  test cases/failing/88 dub compiler/test.json
  test cases/frameworks/1 boost/meson.build
Labels: CI

#6875 ci: Fix Azure timeouts with self-hosted dependency bundle
  ci/azure-steps.yml
  ci/install-dmd.ps1
  ci/run.ps1
Labels: CI

#6896 qt dependency: Pick debug libraries based on b_vscrt
  mesonbuild/dependencies/ui.py
  run_unittests.py
Labels: qt, windows

#6231 CI fortran: first_supported_argument, get_supported_arguments
  mesonbuild/compilers/fortran.py
  mesonbuild/compilers/mixins/clike.py
  mesonbuild/interpreter.py
  test cases/fortran/18 first_arg/main.f90
  test cases/fortran/18 first_arg/meson.build
Labels: CI, refactoring

#6909 boost: Fix library version (fixes #6899)
  mesonbuild/dependencies/boost.py
Labels: boost

#6901 ci: Travis: Use the new mesonbuild/eoan image
  .travis.yml
Labels: CI

#6913 travis: Fix Travis OSX build
  .travis.yml
  ci/travis_install.sh
  ci/travis_script.sh
Labels: CI

#6938 ci: Fix passing env vars
  .github/workflows/os_comp.yml
Labels: CI

#6952 opts: Allow `-` and `not` in meson_options.txt (fixes #6948)
  mesonbuild/optinterpreter.py
  test cases/common/43 options/meson.build
  test cases/common/43 options/meson_options.txt
Labels: options

#6945 Fix VS Intellisense for projects which depend on LLVM found via CMake.
  mesonbuild/dependencies/dev.py
Labels: cmake, dependencies

#6957 azure: Do not skip boost tests
  ci/run.ps1
Labels: CI

#6961 cmake: Preserve include directory order (fixes #6959)
  mesonbuild/cmake/interpreter.py
  test cases/cmake/17 include path order/main.cpp
  test cases/cmake/17 include path order/meson.build
  test cases/cmake/17 include path order/subprojects/cmMod/CMakeLists.txt
  test cases/cmake/17 include path order/subprojects/cmMod/cmMod.cpp
  test cases/cmake/17 include path order/subprojects/cmMod/incA/cmMod.hpp
  test cases/cmake/17 include path order/subprojects/cmMod/incB/cmMod.hpp
  test cases/cmake/17 include path order/subprojects/cmMod/incC/cmMod.hpp
  test cases/cmake/17 include path order/subprojects/cmMod/incD/cmMod.hpp
  test cases/cmake/17 include path order/subprojects/cmMod/incE/cmMod.hpp
  test cases/cmake/17 include path order/subprojects/cmMod/incF/cmMod.hpp
  test cases/cmake/17 include path order/subprojects/cmMod/incG/cmMod.hpp
  test cases/cmake/17 include path order/subprojects/cmMod/incH/cmMod.hpp
  test cases/cmake/17 include path order/subprojects/cmMod/incI/cmMod.hpp
  test cases/cmake/17 include path order/subprojects/cmMod/incJ/cmMod.hpp
  test cases/cmake/17 include path order/subprojects/cmMod/incL/cmMod.hpp
  test cases/cmake/17 include path order/subprojects/cmMod/incM/cmMod.hpp
  test cases/cmake/17 include path order/subprojects/cmMod/incN/cmMod.hpp
  test cases/cmake/17 include path order/subprojects/cmMod/incO/cmMod.hpp
  test cases/cmake/17 include path order/subprojects/cmMod/incP/cmMod.hpp
Labels: cmake, subprojects/wraps

#6943 Fix coverage generation with D compilers
  mesonbuild/compilers/compilers.py
  mesonbuild/compilers/d.py
  mesonbuild/compilers/mixins/clike.py
  mesonbuild/compilers/mixins/gnu.py
Labels: D language

#6963 cmake: some fixes for add_custom_command
  mesonbuild/cmake/data/run_ctgt.py
  mesonbuild/cmake/traceparser.py
  test cases/cmake/8 custom command/subprojects/cmMod/CMakeLists.txt
  test cases/cmake/8 custom command/subprojects/cmMod/genMain.cpp
Labels: cmake, subprojects/wraps

#6983 tests/common/93: Fix cross building when no exe_wrapper is available
  test cases/common/93 selfbuilt custom/meson.build
Labels: meson tests

#6986 docs: Add XTS (X Test Suite) to users and updated freedesktop to gitlab [skip ci]
  docs/markdown/Users.md
Labels: documentation

#6981 cmake: Do not compile explicit header files
  mesonbuild/cmake/data/preload.cmake
  mesonbuild/cmake/interpreter.py
  mesonbuild/cmake/traceparser.py
  test cases/cmake/18 skip include files/main.cpp
  test cases/cmake/18 skip include files/meson.build
  test cases/cmake/18 skip include files/subprojects/cmMod/CMakeLists.txt
  test cases/cmake/18 skip include files/subprojects/cmMod/cmMod.cpp
  test cases/cmake/18 skip include files/subprojects/cmMod/cmMod.hpp
  test cases/cmake/18 skip include files/subprojects/cmMod/fakeInc/CMakeLists.txt
  test cases/cmake/18 skip include files/subprojects/cmMod/fakeInc/cmModInc1.cpp
  test cases/cmake/18 skip include files/subprojects/cmMod/fakeInc/cmModInc2.cpp
  test cases/cmake/18 skip include files/subprojects/cmMod/fakeInc/cmModInc3.cpp
  test cases/cmake/18 skip include files/subprojects/cmMod/fakeInc/cmModInc4.cpp
Labels: cmake, subprojects/wraps

#5489 Compiler options per lang
  mesonbuild/backend/backends.py
  mesonbuild/backend/ninjabackend.py
  mesonbuild/backend/vs2010backend.py
  mesonbuild/build.py
  mesonbuild/compilers/c.py
  mesonbuild/compilers/compilers.py
  mesonbuild/compilers/cpp.py
  mesonbuild/compilers/fortran.py
  mesonbuild/coredata.py
  mesonbuild/environment.py
  mesonbuild/interpreter.py
  mesonbuild/mconf.py
  mesonbuild/mintro.py
  mesonbuild/rewriter.py
  run_tests.py
  run_unittests.py
Labels: options

#7001 docs/cross-compilation: Note appropriate values for cpu_family [skip ci]
  docs/markdown/Cross-compilation.md
Labels: documentation

#6816 project test junit schema + a few more uses
  .editorconfig
  .github/workflows/os_comp.yml
  azure-pipelines.yml
  ci/ciimage/arch/install.sh
  ci/run.ps1
  ci/travis_install.sh
  data/test.schema.json
  docs/markdown/Contributing.md
  run_project_tests.py
  run_unittests.py
  test cases/frameworks/16 sdl2/meson.build
  test cases/frameworks/16 sdl2/meson_options.txt
  test cases/frameworks/16 sdl2/test.json
  test cases/frameworks/17 mpi/test.json
Labels: meson tests

#7010 Issue: 7009: CMake/Centos7 Unable to find CMake even though it is installed
  mesonbuild/cmake/executor.py
Labels: cmake

#7015 Adjust regex to handle cases such as C:/Program Files/
  mesonbuild/cmake/traceparser.py
Labels: cmake

#7018 mtest: Generate JUnit results for tests
  ci/ciimage/arch/install.sh
  ci/ciimage/eoan/install.sh
  ci/ciimage/fedora/install.sh
  ci/ciimage/opensuse/install.sh
  data/schema.xsd
  docs/markdown/snippets/junit_result_generation.md
  mesonbuild/mtest.py
  run_unittests.py
Labels: test targets

#6911 ci: Add Ubuntu Bionic image
  .github/workflows/images.yml
  .github/workflows/os_comp.yml
  ci/ciimage/bionic/image.json
  ci/ciimage/bionic/install.sh
  ci/ciimage/build.py
  ci/ciimage/opensuse/install.sh
  docs/markdown/Contributing.md
  run_project_tests.py
  test cases/cmake/2 advanced/test.json
  test cases/cmake/3 advanced no dep/test.json
  test cases/frameworks/23 hotdoc/test.json
  test cases/linuxlike/13 cmake dependency/cmVers.sh
  test cases/linuxlike/13 cmake dependency/meson.build
Labels: CI

#7050 CI: pin pylint
  .github/workflows/lint_mypy.yml
Labels: CI
