Repository mesonbuild/meson, pull requests merged in 2021-06, with the labels that each got.

#8825 test cases/common/103 has header symbol: set c++ standard
  test cases/common/103 has header symbol/meson.build
Labels: OS:macos

#8840 typing: Fully annotate dependencies.pkgconfig
  mesonbuild/dependencies/pkgconfig.py
  run_mypy.py
Labels: typing

#8835 typing: Fully annotate dependencies.cmake
  mesonbuild/dependencies/cmake.py
  run_mypy.py
Labels: typing

#8839 typing: Fully annotate dependencies.{detect,factory} + some other fixes
  mesonbuild/coredata.py
  mesonbuild/dependencies/coarrays.py
  mesonbuild/dependencies/detect.py
  mesonbuild/dependencies/factory.py
  mesonbuild/dependencies/hdf5.py
  mesonbuild/dependencies/misc.py
  mesonbuild/dependencies/mpi.py
  mesonbuild/dependencies/scalapack.py
  run_mypy.py
Labels: typing

#8842 typing: Fully annotate dependencies.framework
  mesonbuild/dependencies/framework.py
  run_mypy.py
Labels: typing

#8847 ci: Fix CI image builder
  ci/ciimage/arch/install.sh
  ci/ciimage/bionic/install.sh
  ci/ciimage/common.sh
  ci/ciimage/cuda/install.sh
  ci/ciimage/fedora/install.sh
  ci/ciimage/opensuse/install.sh
  ci/ciimage/ubuntu-rolling/install.sh
  ci/ciimage/ubuntu-rolling/test.sh
Labels: CI

#8878 Fix System dependencies setting type_name instead of name
  mesonbuild/dependencies/base.py
  mesonbuild/dependencies/boost.py
  mesonbuild/dependencies/cmake.py
  mesonbuild/dependencies/coarrays.py
  mesonbuild/dependencies/configtool.py
  mesonbuild/dependencies/cuda.py
  mesonbuild/dependencies/dev.py
  mesonbuild/dependencies/dub.py
  mesonbuild/dependencies/factory.py
  mesonbuild/dependencies/framework.py
  mesonbuild/dependencies/misc.py
  mesonbuild/dependencies/mpi.py
  mesonbuild/dependencies/pkgconfig.py
  mesonbuild/dependencies/platform.py
  mesonbuild/dependencies/system.py
  mesonbuild/dependencies/ui.py
  mesonbuild/modules/python.py
  run_mypy.py
  test cases/failing/68 wrong boost module/test.json
Labels: dependencies, typing

#8908 fix: Ensure that build targets have all methods from ExternalProgram
  docs/markdown/Reference-manual.md
  docs/markdown/snippets/build-target-found.md
  mesonbuild/interpreter/interpreterobjects.py
  mesonbuild/interpreterbase/baseobjects.py
  test cases/common/182 find override/meson.build
  test cases/common/182 find override/otherdir/meson.build
Labels: regression

#8803 Add Visual Studio 2012/2013 backends
  docs/markdown/Builtin-options.md
  docs/markdown/Reference-manual.md
  docs/markdown/snippets/newvsbackends.md
  mesonbuild/backend/backends.py
  mesonbuild/backend/vs2010backend.py
  mesonbuild/backend/vs2012backend.py
  mesonbuild/backend/vs2013backend.py
  mesonbuild/cmake/common.py
  mesonbuild/coredata.py
  test cases/common/137 whole archive/meson.build
Labels: backend:visualstudio

#8894 coverage: Enable coverage reports
  .coveragerc
  .github/workflows/cygwin.yml
  .github/workflows/macos.yml
  .github/workflows/msys2.yml
  .github/workflows/nonative.yml
  .github/workflows/os_comp.yml
  .github/workflows/unusedargs_missingreturn.yml
  .gitignore
  azure-pipelines.yml
  ci/run.ps1
  ci/upload_cov.sh
  ci/usercustomize.py
  data/.coveragerc.in
  run_tests.py
  run_unittests.py
  tools/run_with_cov.py
Labels: CI

#8905 fix: Fix set_variable not holderifying (fixes #8904)
  mesonbuild/interpreter/interpreter.py
  mesonbuild/interpreterbase/interpreterbase.py
  test cases/common/242 set and get variable/meson.build
  test cases/common/242 set and get variable/test1.txt
  test cases/common/242 set and get variable/test2.txt
Labels: regression

#8912 Fix `BothLibraries` processing
  .github/workflows/os_comp.yml
  mesonbuild/build.py
  mesonbuild/dependencies/base.py
  mesonbuild/interpreter/interpreter.py
  mesonbuild/interpreter/interpreterobjects.py
  mesonbuild/modules/gnome.py
  test cases/common/102 extract same name/meson.build
  test cases/common/126 generated llvm ir/meson.build
  test cases/common/127 generated assembly/meson.build
  test cases/common/146 library at root/meson.build
  test cases/common/153 wrap file should not failed/subprojects/zlib-1.2.8/meson.build
  test cases/common/155 subproject dir name collision/custom_subproject_dir/B/meson.build
  test cases/common/155 subproject dir name collision/custom_subproject_dir/C/meson.build
  test cases/common/155 subproject dir name collision/other_subdir/meson.build
  test cases/common/167 subproject nested subproject dirs/contrib/subprojects/alpha/meson.build
  test cases/common/178 bothlibraries/dummy.py
  test cases/common/178 bothlibraries/meson.build
  test cases/common/22 object extraction/meson.build
  test cases/common/223 persubproject options/meson.build
  test cases/common/223 persubproject options/test.json
  test cases/common/72 shared subproject/subprojects/B/meson.build
  test cases/common/72 shared subproject/subprojects/C/meson.build
  test cases/common/73 shared subproject 2/subprojects/B/meson.build
  test cases/common/73 shared subproject 2/subprojects/C/meson.build
  test cases/failing/16 extract from subproject/subprojects/sub_project/meson.build
  test cases/fortran/21 install static/meson.build
  test cases/fortran/21 install static/test.json
  test cases/frameworks/10 gtk-doc/meson.build
  test cases/linuxlike/5 dependency versions/subprojects/somelib/meson.build
  test cases/linuxlike/5 dependency versions/subprojects/somelibnover/meson.build
  test cases/linuxlike/5 dependency versions/subprojects/somelibver/meson.build
  test cases/rust/4 polyglot/meson.build
Labels: regression

#8884 Add annotations for the various install_* functions
  mesonbuild/backend/backends.py
  mesonbuild/build.py
  mesonbuild/interpreter/interpreter.py
  mesonbuild/interpreter/kwargs.py
  mesonbuild/interpreterbase/decorators.py
  mesonbuild/mesonlib/universal.py
  mesonbuild/minstall.py
  run_unittests.py
  test cases/failing/30 invalid man extension/test.json
  test cases/failing/31 no man extension/test.json
  test cases/failing/95 custom target install data/test.json
Labels: typing

#8933 refactor: Refactor BothLibraries logic
  mesonbuild/build.py
  mesonbuild/dependencies/base.py
  mesonbuild/interpreter/interpreter.py
  mesonbuild/interpreter/interpreterobjects.py
  mesonbuild/interpreterbase/__init__.py
  mesonbuild/interpreterbase/baseobjects.py
  mesonbuild/interpreterbase/decorators.py
  mesonbuild/interpreterbase/helpers.py
  mesonbuild/interpreterbase/interpreterbase.py
  mesonbuild/mesonlib/universal.py
  mesonbuild/modules/gnome.py
  mesonbuild/modules/pkgconfig.py
  test cases/common/178 bothlibraries/meson.build
Labels: refactoring

#8921 modules/qt: use _impl private methods to avoid incorrect FeatureNew
  mesonbuild/modules/qt.py
Labels: module:qt

#8899 build: fix object path for vs backend
  mesonbuild/backend/backends.py
  test cases/common/121 object only target/meson.build
  test cases/common/121 object only target/objdir/meson.build
  test cases/common/121 object only target/objdir/source4.c
  test cases/common/121 object only target/objdir/source5.c
  test cases/common/121 object only target/objdir/source6.c
  test cases/common/121 object only target/prog.c
Labels: backend:visualstudio
