Repository mesonbuild/meson, pull requests merged in 2021-03, with the labels that each got.

#8438 d_import_dirs add search path in the build directory
  mesonbuild/compilers/d.py
Labels: language:D

#5460 docs/faq: Add a section on user defined functions and macros [skip ci]
  docs/markdown/FAQ.md
Labels: documentation

#8435 fix missing D versions with generated source
  mesonbuild/compilers/d.py
Labels: language:D

#8453 Windows Subsystem for Linux can run .exe without mono interpreter
  mesonbuild/backend/backends.py
  mesonbuild/mesonlib/universal.py
Labels: OS:windows

#8467 mintro: include the correct target filenames for flat layout
  mesonbuild/mintro.py
  run_unittests.py
Labels: introspection

#8468 ci: Downgrade Qt on MacOS from Qt6 to Qt5
  .github/workflows/macos.yml
Labels: CI

#8500 change RSP quote style decision logic
  mesonbuild/backend/ninjabackend.py
Labels: language:D

#8504 Add test to build a mixed C/Rust shared library.
  test cases/rust/15 polyglot sharedlib/adder.c
  test cases/rust/15 polyglot sharedlib/adder.h
  test cases/rust/15 polyglot sharedlib/adder.rs
  test cases/rust/15 polyglot sharedlib/addertest.c
  test cases/rust/15 polyglot sharedlib/meson.build
Labels: language:rust

#8520 compilers: clang-cl: Also accept .s files
  mesonbuild/compilers/mixins/visualstudio.py
  test cases/common/128 generated assembly/empty.c
  test cases/common/128 generated assembly/meson.build
  test cases/common/128 generated assembly/square-x86.S.in
  test cases/common/128 generated assembly/square-x86_64.S.in
  test cases/common/128 generated assembly/square.def
Labels: compilers

#8568 QT: use a proper dependency factory
  docs/markdown/snippets/qt_factory.md
  mesonbuild/dependencies/__init__.py
  mesonbuild/dependencies/base.py
  mesonbuild/dependencies/qt.py
  mesonbuild/dependencies/ui.py
  mesonbuild/modules/qt.py
  run_mypy.py
  run_project_tests.py
  run_single_test.py
  run_unittests.py
  test cases/frameworks/4 qt/test.json
Labels: dependencies, qt
