Repository mesonbuild/meson, pull requests merged in 2022-12, with the labels that each got.

#11024 Add a `dependencies` keyword argument to bindgen
  docs/markdown/Rust-module.md
  docs/markdown/snippets/rust_bindgen_deps.md
  mesonbuild/modules/rust.py
  test cases/rust/12 bindgen/dependencies/clib2.c
  test cases/rust/12 bindgen/dependencies/external_dep.h
  test cases/rust/12 bindgen/dependencies/internal_dep.h
  test cases/rust/12 bindgen/dependencies/internal_main.rs
  test cases/rust/12 bindgen/dependencies/meson.build
  test cases/rust/12 bindgen/meson.build
Labels: module:rust

#11151 Revert "openbsd: execinfo is not a compiler lib"
  mesonbuild/arglist.py
Labels: OS:*BSD

#11201 meson: Cache os.path.realpath in CLikeCompilerArgs
  mesonbuild/compilers/mixins/clike.py
Labels: perf

#11150 use static_library's pic calculation instead of recalculating
  mesonbuild/interpreter/interpreter.py
Labels: refactoring
