Repository mesonbuild/meson, pull requests merged in 2022-07, with the labels that each got.

#10550 gnome module: Use --quiet to supress printing the link command line
  mesonbuild/modules/gnome.py
Labels: module:gnome

#10575 run_single_test: Allow passing extra args like run_project_test
  run_single_test.py
Labels: meson tests

#10602 wrap: Fix diff_files not finding the patch to apply
  mesonbuild/wrap/wrap.py
Labels: subprojects/wraps
