Repository mesonbuild/meson, pull requests merged in 2023-08, with the labels that each got.

#12111 use typed_kwargs for exclusive SharedLibrary keyword arguments
  mesonbuild/build.py
  mesonbuild/interpreter/kwargs.py
  mesonbuild/interpreter/type_checking.py
Labels: typing

#11745 Allow users to target Py_LIMITED_API via python's extension_module
  data/test.schema.json
  docs/markdown/Builtin-options.md
  docs/markdown/Python-module.md
  docs/markdown/snippets/python_extension_module_limited_api.md
  mesonbuild/coredata.py
  mesonbuild/dependencies/python.py
  mesonbuild/modules/python.py
  mesonbuild/scripts/python_info.py
  run_project_tests.py
  test cases/python/10 extmodule limited api disabled/meson.build
  test cases/python/10 extmodule limited api disabled/module.c
  test cases/python/9 extmodule limited api/limited.c
  test cases/python/9 extmodule limited api/meson.build
  test cases/python/9 extmodule limited api/not_limited.c
  test cases/python/9 extmodule limited api/test.json
Labels: modules:python

#12087 Add fs.relative_to()
  docs/markdown/Fs-module.md
  docs/markdown/snippets/fs_relative_to.md
  mesonbuild/modules/fs.py
  test cases/common/220 fs module/meson.build
  test cases/common/220 fs module/subdir/btgt.c
  test cases/common/220 fs module/subdir/meson.build
Labels: module:fs
