Repository mesonbuild/meson, pull requests merged in 2023-10, with the labels that each got.

#12320 nasm tests: skip asm language test on Solaris & illumos
  test cases/nasm/2 asm language/meson.build
Labels: OS:solaris/illumos

#12337 msubprojects: Fix conditions around rebase on update
  mesonbuild/msubprojects.py
Labels: subprojects/wraps

#12364 ninjabackend: Use the right ranlib for static linker rules on macOS
  mesonbuild/backend/ninjabackend.py
Labels: OS:macos

#12389 test cases/15 llvm: Disable cmake on clangx64ninja
  test cases/frameworks/15 llvm/meson.build
  test cases/frameworks/15 llvm/test.json
Labels: dependency:cmake
