Repository mesonbuild/meson, pull requests merged in 2023-03, with the labels that each got.

#11467 rust: Store absolute paths in rust-project.json
  mesonbuild/backend/ninjabackend.py
Labels: language:rust

#11515 utils: fix annotation of pickle_load
  mesonbuild/coredata.py
  mesonbuild/minstall.py
  mesonbuild/utils/universal.py
Labels: refactoring, typing

#11626 fix regression that broken git-based wraps with dirty contents
  mesonbuild/msubprojects.py
Labels: regression
