Repository mesonbuild/meson, pull requests merged in 2024-10, with the labels that each got.

#13750 Fix C++ standard support for Emscripten
  mesonbuild/compilers/cpp.py
  test cases/wasm/1 basic/meson.build
Labels: Arch:Wasm

#13751 docs: Add windres to cross-compiling example
  docs/markdown/Cross-compilation.md
Labels: documentation

#13792 Update release notes for 1.6.0
  docs/markdown/snippets/add_support_for_ibm_clang_for_AIX.md
Labels: documentation

#13815 Reimplement several methods for Fortran compilers
  docs/markdown/snippets/fixed_sizeof_and_find_library_for_fortran.md
  mesonbuild/compilers/fortran.py
Labels: language:fortran

#13838 Correct typo in example Python module option
  docs/markdown/Python-module.md
Labels: documentation
