Repository mesonbuild/meson, pull requests merged in 2024-02, with the labels that each got.

#12724 Fix minsize optimization for vs backend
  mesonbuild/backend/vs2010backend.py
Labels: backend:visualstudio

#12692 doc: benchmark: correct usage on unix
  docs/yaml/functions/benchmark.yaml
Labels: documentation

#11795 qt: add preserve_paths keyword to functions
  docs/markdown/Qt6-module.md
  docs/markdown/_include_qt_base.md
  docs/markdown/snippets/qt_preserve_path_from.md
  mesonbuild/modules/qt.py
  test cases/frameworks/4 qt/mainWindow.h
  test cases/frameworks/4 qt/meson.build
  test cases/frameworks/4 qt/ui/mainWindow.ui
Labels: module:qt

#12848 type annotations and typechecking for CUDA module
  mesonbuild/modules/cuda.py
  run_mypy.py
Labels: typing, module:cuda

#12856 docs: Remove outdated HDF5 dependency pkg-config statement
  docs/markdown/Dependencies.md
Labels: documentation

#12825 Fix KeyError in Python module
  mesonbuild/modules/python.py
  test cases/python/5 modules kwarg/a.py
  test cases/python/5 modules kwarg/meson.build
  test cases/python/5 modules kwarg/test.json
Labels: bug, modules:python

#12697 Fix base options not reconfigurable
  mesonbuild/coredata.py
Labels: bug, options

#12744 doc: fix compiler.preprocess varargs documentation
  docs/yaml/objects/compiler.yaml
Labels: documentation

#12409 Add FS module support for CustomTarget, CustomTargetIndex, and BuildTarget
  docs/markdown/snippets/additional_types_for_fs_module.md
  mesonbuild/modules/fs.py
  test cases/common/220 fs module/btgt.c
  test cases/common/220 fs module/ctgt.txt
  test cases/common/220 fs module/meson.build
Labels: module:fs

#12782 rewriter: allow setting values regardless of the previous type
  mesonbuild/rewriter.py
Labels: rewriter
