Repository mesonbuild/meson, pull requests merged in 2025-04, with the labels that each got.

#10238 wayland: Mark module stable
  docs/markdown/Wayland-module.md
  mesonbuild/modules/wayland.py
Labels: mesa/wayland/xorg

#14431 modules/cmake: Make fully type safe
  mesonbuild/modules/cmake.py
  run_mypy.py
Labels: refactoring, typing

#14409 docs: fix default for `meson format` `sort_files` option
  docs/markdown/Commands.md
Labels: documentation, tool:format

#13505 Docs: Cleaner admonishment styling
  docs/refman/templates/notes.mustache
  docs/theme/extra/css/notes.css
Labels: documentation

#14448 Docs: Set note/warning title color to black text
  docs/theme/extra/css/notes.css
Labels: documentation

#14456 docs: say '--wrapper', not '--wrap' for tests
  docs/markdown/Unit-tests.md
Labels: documentation

#14457 Add C# to home page supported language list
  docs/markdown/index.md
Labels: documentation

#14459 Fix documentation typos
  docs/markdown/Build-options.md
  docs/markdown/Builtin-options.md
  docs/markdown/FAQ.md
  docs/markdown/IDE-integration.md
  docs/markdown/Include-directories.md
  docs/markdown/Qt6-module.md
  docs/markdown/Unit-tests.md
Labels: documentation

#14424 interpreter: Error if java sources used with non-jar target
  mesonbuild/compilers/__init__.py
  mesonbuild/compilers/compilers.py
  mesonbuild/interpreter/interpreter.py
  test cases/failing/134 java sources in non jar target/Test.java
  test cases/failing/134 java sources in non jar target/meson.build
  test cases/failing/134 java sources in non jar target/test.json
Labels: language:java

#14472 linkers: fix Apple ld -install_name with custom suffix
  mesonbuild/linkers/linkers.py
Labels: bug, OS:macos, dynamic linkers

#14347 add exe_wrapper to the wasm cross file
  cross/wasm.txt
Labels: Arch:Wasm

#14489 Fix behavior with options whose prefix is a builtin option name
  mesonbuild/mesonmain.py
  test cases/unit/128 long opt vs D/meson.build
  test cases/unit/128 long opt vs D/meson_options.txt
  unittests/allplatformstests.py
Labels: regression, options

#12861 determine_windows_extra_paths: append external dependencies after internal ones
  mesonbuild/backend/backends.py
Labels: OS:windows

#14342 avoid false positive PermissionError in declare_dependency
  mesonbuild/interpreter/interpreter.py
  test cases/unit/125 declare_dep var/meson.build
  test cases/unit/125 declare_dep var/meson_options.txt
  unittests/linuxliketests.py
Labels: bug, pathlib, exception

#14508 Fix meson format with multi line parenthesized expressions
  mesonbuild/mformat.py
  test cases/format/5 transform/default.expected.meson
  test cases/format/5 transform/muon.expected.meson
  test cases/format/5 transform/options.expected.meson
  test cases/format/5 transform/source.meson
Labels: tool:format

#14526 unittests: fix overly loose regex in tests for `--slice=` option
  unittests/allplatformstests.py
Labels: bug, meson tests

#14379 improve and unify logging for sanity checks
  mesonbuild/compilers/compilers.py
  mesonbuild/compilers/cs.py
  mesonbuild/compilers/cuda.py
  mesonbuild/compilers/d.py
  mesonbuild/compilers/java.py
  mesonbuild/compilers/mixins/clike.py
  mesonbuild/compilers/rust.py
  mesonbuild/compilers/swift.py
Labels: compilers
