Repository mesonbuild/meson, pull requests merged in 2025-01, with the labels that each got.

#13901 fix missing extension in command path
  mesonbuild/programs.py
Labels: OS:windows

#13304 Qml modules
  docs/markdown/Qt6-module.md
  mesonbuild/interpreter/interpreter.py
  mesonbuild/modules/_qt.py
  test cases/frameworks/39 qt qml/Basic.qml
  test cases/frameworks/39 qt qml/Internal.qml
  test cases/frameworks/39 qt qml/Main.qml
  test cases/frameworks/39 qt qml/QmlCppExposed.hpp
  test cases/frameworks/39 qt qml/QmlCppOtherExposed.hpp
  test cases/frameworks/39 qt qml/QmlMain.cpp
  test cases/frameworks/39 qt qml/QmlSingleton.qml
  test cases/frameworks/39 qt qml/custom_qmldir
  test cases/frameworks/39 qt qml/custom_qmldir.qrc
  test cases/frameworks/39 qt qml/meson.build
  test cases/frameworks/39 qt qml/meson_options.txt
  test cases/frameworks/39 qt qml/subdir/SubdirHeader.hpp
  test cases/frameworks/39 qt qml/subdir/Thing.qml
  test cases/frameworks/39 qt qml/test.json
Labels: module:qt

#14098 Fix broken both_libraries transitive dependencies
  mesonbuild/build.py
  mesonbuild/dependencies/base.py
  test cases/common/273 both libraries/meson.build
Labels: regression

#14164 linkers: fix rpath padding calculation for non-ascii
  mesonbuild/linkers/linkers.py
  test cases/unit/10 build_rpath/meson.build
Labels: install targets, dynamic linkers

#14195 docs: clarify behavior of default_both_libraries option
  docs/markdown/Builtin-options.md
Labels: documentation

#13642 Support lists for ObjC and ObjC++ standards
  mesonbuild/compilers/c.py
  mesonbuild/compilers/cpp.py
  mesonbuild/compilers/detect.py
  mesonbuild/compilers/mixins/apple.py
  mesonbuild/compilers/mixins/clang.py
  mesonbuild/compilers/mixins/gnu.py
  mesonbuild/compilers/objc.py
  mesonbuild/compilers/objcpp.py
  test cases/unit/116 c cpp stds/meson.build
  test cases/unit/116 c cpp stds/meson.options
  unittests/allplatformstests.py
  unittests/baseplatformtests.py
  unittests/failuretests.py
  unittests/machinefiletests.py
Labels: language:objc, language:objc++

#14145 Detect missing files with trailing space on Windows
  mesonbuild/interpreter/interpreter.py
  mesonbuild/utils/universal.py
Labels: OS:windows

#13376 swift: Fix compilation error when dependency adds the macOS SDK in the include dirs
  mesonbuild/compilers/swift.py
  test cases/swift/9 sdk path from dep/foo.swift
  test cases/swift/9 sdk path from dep/meson.build
Labels: OS:macos, pkgconfig, language:swift

#14205 Fix call to object_filename_from_source in vs2010
  mesonbuild/backend/vs2010backend.py
Labels: regression, backend:visualstudio

#14186 Mention add_dist_script in meson dist docs
  docs/markdown/Creating-releases.md
Labels: documentation

#14019 Cleanup PerMachine classes, especially nullability
  mesonbuild/utils/universal.py
Labels: refactoring, typing

#14178 mformat: try to detect meson.format in parent directories
  mesonbuild/mformat.py
Labels: tool:format
